require("catppuccin").setup({
  transparent_background = false,
  color_overrides = {
    mocha = {
      base = "#111114",
      mantle = "#17171c",
      crust = "#0d0d10",
      surface0 = "#24242a",
      surface1 = "#2f2f36",
      surface2 = "#3a3a42",
      overlay0 = "#747480",
      overlay1 = "#8d8d99",
      overlay2 = "#a7a7b0",
      red = "#ff6363",
      maroon = "#ff7a7a",
      pink = "#f38ba8",
      peach = "#f7c66f",
    },
  },
  custom_highlights = function(colors)
    local raycast_red = "#ff6363"
    local raycast_red_dim = "#3a2027"
    local raycast_bg = "#111114"
    local raycast_panel = "#17171c"
    local raycast_focus = "#202029"
    local raycast_surface = "#24242a"
    local raycast_surface_active = "#2f2f36"

    return {
      Normal = { bg = raycast_bg },
      NormalNC = { bg = raycast_bg },
      SignColumn = { bg = raycast_bg },
      EndOfBuffer = { fg = colors.surface0, bg = raycast_bg },
      Cursor = { bg = raycast_red, fg = raycast_bg },
      CursorLine = { bg = raycast_focus },
      CursorColumn = { bg = raycast_panel },
      CursorLineNr = { fg = raycast_red, bg = raycast_focus, style = { "bold" } },
      LineNr = { fg = colors.overlay0 },
      Visual = { bg = raycast_red_dim },
      Search = { bg = raycast_red, fg = raycast_bg, style = { "bold" } },
      IncSearch = { bg = colors.peach, fg = raycast_bg, style = { "bold" } },
      CurSearch = { bg = raycast_red, fg = raycast_bg, style = { "bold" } },
      MatchParen = { bg = raycast_surface, fg = raycast_red, style = { "bold" } },
      StatusLine = { bg = raycast_panel, fg = colors.text },
      StatusLineNC = { bg = raycast_bg, fg = colors.overlay0 },
      StatusLineTerm = { bg = raycast_panel, fg = colors.text },
      StatusLineTermNC = { bg = raycast_surface, fg = colors.overlay0 },
      WinSeparator = { fg = raycast_surface_active },
      FloatBorder = { fg = raycast_red, bg = "NONE" },
      NormalFloat = { bg = raycast_panel },
      Pmenu = { bg = raycast_surface, fg = colors.text },
      PmenuSel = { bg = raycast_red, fg = raycast_bg, style = { "bold" } },
      TabLine = { bg = raycast_panel, fg = colors.overlay1 },
      TabLineSel = { bg = raycast_red, fg = raycast_bg, style = { "bold" } },
      TabLineFill = { bg = raycast_bg },
      TelescopeBorder = { fg = raycast_surface_active, bg = raycast_panel },
      TelescopeNormal = { bg = raycast_panel },
      TelescopePromptBorder = { fg = raycast_red, bg = raycast_panel },
      TelescopeSelection = { bg = raycast_surface, fg = colors.text, style = { "bold" } },
      TelescopeSelectionCaret = { fg = raycast_red },
      TelescopeMatching = { fg = raycast_red, style = { "bold" } },
      NvimTreeNormal = { bg = raycast_panel },
      NvimTreeNormalNC = { bg = raycast_panel },
      NvimTreeEndOfBuffer = { fg = raycast_panel, bg = raycast_panel },
      NvimTreeCursorLine = { bg = raycast_surface_active },
      NvimTreeFolderIcon = { fg = raycast_red },
      NvimTreeOpenedFolderName = { fg = raycast_red, style = { "bold" } },
      NvimTreeRootFolder = { fg = raycast_red, style = { "bold" } },
      BufferCurrent = { bg = raycast_red, fg = raycast_bg, style = { "bold" } },
      BufferCurrentIndex = { bg = raycast_red, fg = raycast_bg },
      BufferCurrentMod = { bg = raycast_red, fg = raycast_bg },
      BufferCurrentSign = { bg = raycast_red, fg = raycast_bg },
      BufferCurrentTarget = { bg = raycast_red, fg = raycast_bg, style = { "bold" } },
      BufferVisible = { bg = raycast_panel, fg = colors.overlay2 },
      BufferVisibleIndex = { bg = raycast_panel, fg = colors.overlay0 },
      BufferVisibleMod = { bg = raycast_panel, fg = colors.overlay2 },
      BufferVisibleSign = { bg = raycast_panel, fg = raycast_red },
      BufferVisibleTarget = { bg = raycast_panel, fg = raycast_red },
      BufferInactive = { bg = raycast_bg, fg = colors.overlay0 },
      BufferInactiveIndex = { bg = raycast_bg, fg = colors.overlay0 },
      BufferInactiveMod = { bg = raycast_bg, fg = colors.overlay0 },
      BufferInactiveSign = { bg = raycast_bg, fg = raycast_surface_active },
      BufferInactiveTarget = { bg = raycast_bg, fg = raycast_red },
      BufferTabpageFill = { bg = raycast_bg },
      BufferOffset = { bg = raycast_panel, fg = colors.overlay1 },
    }
  end,
  integrations = {
    telescope = true,
    harpoon = true,
    mason = true,
    neotest = true,
  }
})
vim.cmd("colorscheme catppuccin-mocha")
